version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: FiberShop
      POSTGRES_PASSWORD: FiberShop
      POSTGRES_DB: FiberShop
    networks:
      - auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  auth:

volumes:
  postgres_data: