version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: FiberShop
      POSTGRES_PASSWORD: FiberShop
      POSTGRES_DB: FiberShop
    networks:
      - shop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - shop
    volumes:
      - redis_data:/FiberShop/data
networks:
  shop:

volumes:
  postgres_data:
  redis_data: