version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - shop
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - shop
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - shop
    volumes:
      - redis_data:/FiberShop/data
  
  auth:
    image: gosmach1ne/serviceauth
    ports:
      - "44043:44043"
    networks:
      - shop
    env_file:
      - .env
    depends_on:
      - postgres
networks:
  shop:

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: