version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FiberShop
    networks:
      - shop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - shop
    volumes:
      - redis_data:/FiberShop/data
  
  auth:
    image: gosmach1ne/serviceauth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: FiberShop
      POSTGRES_PORT: 5432
    ports:
      - "44043:44043"
    networks:
      - shop
    depends_on:
      - postgres
networks:
  shop:

volumes:
  postgres_data:
  redis_data: