// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package alerts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "FiberShop/web/view/layout"

func hideAlert(button, containerId string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_hideAlert_bf82`,
		Function: `function __templ_hideAlert_bf82(button, containerId){var button = document.getElementById(button);
        button.disabled = true;
        setTimeout(() => {
            var alertContainer = document.getElementById(containerId)

            alertContainer.removeAttribute('data-te-toast-show');
            alertContainer.setAttribute('data-te-toast-hide', '');
            button.disabled = false;
        }, 5000);
}`,
		Call:       templ.SafeScript(`__templ_hideAlert_bf82`, button, containerId),
		CallInline: templ.SafeScriptInline(`__templ_hideAlert_bf82`, button, containerId),
	}
}

func Error(alert Alert, data layout.Data) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"pointer-events-auto fixed bottom-5 right-5 max-w-sm mx-auto mb-4 hidden w-78 rounded-lg bg-danger-100 bg-clip-padding text-sm text-danger-700 shadow-lg shadow-black/5 data-[te-toast-show]:block data-[te-toast-hide]:hidden\" id=\"alert-error-container\" role=\"alert\" aria-live=\"assertive\" aria-atomic=\"true\" data-te-autohide=\"false\" data-te-toast-init data-te-toast-show><div class=\"flex items-center justify-between rounded-t-lg border-b-2 border-danger/20 bg-danger-100 bg-clip-padding px-4 pb-2 pt-2.5\"><p class=\"flex items-center font-bold text-danger-700\"><span id=\"alert-error-name\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(alert.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/view/alerts/error_alert.templ`, Line: 30, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></p></div><div id=\"alert-error-message\" class=\"break-words text-[1.1rem] rounded-b-lg bg-danger-100 px-4 py-4 text-danger-700\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(alert.Message)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/view/alerts/error_alert.templ`, Line: 33, Col: 139}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = hideAlert(alert.Button, "alert-error-container").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
